export const emojiToAnimatedPath: Record<string, string> = {
  "🥇": "1st Place Medal.webp",
  "🥈": "2nd Place Medal.webp",
  "🥉": "3rd Place Medal.webp",
  "🧮": "Abacus.webp",
  "🎟️": "Admission Tickets.webp",
  "✈️": "Airplane.webp",
  "👾": "Alien Monster.webp",
  "👽": "Alien.webp",
  "🚑": "Ambulance.webp",
  "💢": "Anger Symbol.webp",
  "👿": "Angry Face With Horns.webp",
  "😠": "Angry Face.webp",
  "😧": "Anguished Face.webp",
  "🐜": "Ant.webp",
  "😰": "Anxious Face With Sweat.webp",
  "♒": "Aquarius.webp",
  "♈": "Aries.webp",
  "🎨": "Artist Palette.webp",
  "😲": "Astonished Face.webp",
  "🚗": "Automobile.webp",
  "🍼": "Baby Bottle.webp",
  "🐤": "Baby Chick.webp",
  "🚼": "Baby Symbol.webp",
  "👶": "Baby.webp",
  "👇": "Backhand Index Pointing Down.webp",
  "👈": "Backhand Index Pointing Left.webp",
  "👉": "Backhand Index Pointing Right.webp",
  "👆": "Backhand Index Pointing Up.webp",
  "🛄": "Baggage Claim.webp",
  "🎈": "Balloon.webp",
  "🗳️": "Ballot Box With Ballot.webp",
  "🍌": "Banana.webp",
  "📊": "Bar Chart.webp",
  "🏀": "Basketball.webp",
  "🦇": "Bat.webp",
  "🏖️": "Beach With Umbrella.webp",
  "😁": "Beaming Face With Smiling Eyes.webp",
  "🐻": "Bear.webp",
  "💓": "Beating Heart.webp",
  "🪲": "Beetle.webp",
  "🍱": "Bento Box.webp",
  "🧃": "Beverage Box.webp",
  "🐦": "Bird.webp",
  "🎂": "Birthday Cake.webp",
  "🦬": "Bison.webp",
  "🫦": "Biting Lip.webp",
  "🐈‍⬛": "Black Cat.webp",
  "🏴": "Black Flag.webp",
  "🖤": "Black Heart.webp",
  "🌼": "Blossom.webp",
  "💙": "Blue Heart.webp",
  "💣": "Bomb.webp",
  "🦴": "Bone.webp",
  "📚": "Books.webp",
  "🍾": "Bottle With Popping Cork.webp",
  "💐": "Bouquet.webp",
  "💼": "Briefcase.webp",
  "💔": "Broken Heart.webp",
  "🤎": "Brown Heart.webp",
  "🧋": "Bubble Tea.webp",
  "🐛": "Bug.webp",
  "👤": "Bust In Silhouette.webp",
  "👥": "Busts In Silhouette.webp",
  "🦋": "Butterfly.webp",
  "🌵": "Cactus.webp",
  "🤙": "Call Me Hand.webp",
  "🏕️": "Camping.webp",
  "♋": "Cancer.webp",
  "🥫": "Canned Food.webp",
  "♑": "Capricorn.webp",
  "🗂️": "Card Index Dividers.webp",
  "🐱": "Cat Face.webp",
  "😹": "Cat With Tears Of Joy.webp",
  "😼": "Cat With Wry Smile.webp",
  "🐈": "Cat.webp",
  "📉": "Chart Decreasing.webp",
  "📈": "Chart Increasing.webp",
  "☑️": "Check Box With Check.webp",
  "✅": "Check Mark Button.webp",
  "✔️": "Check Mark.webp",
  "🏁": "Chequered Flag.webp",
  "🌸": "Cherry Blossom.webp",
  "🐔": "Chicken.webp",
  "🍫": "Chocolate Bar.webp",
  "🎄": "Christmas Tree.webp",
  "🎬": "Clapper Board.webp",
  "👏": "Clapping Hands.webp",
  "🏛️": "Classical Building.webp",
  "🥂": "Clinking Glasses.webp",
  "⛈️": "Cloud With Lightning And Rain.webp",
  "🌩️": "Cloud With Lightning.webp",
  "🌧️": "Cloud With Rain.webp",
  "🌨️": "Cloud With Snow.webp",
  "☁️": "Cloud.webp",
  "🤡": "Clown Face.webp",
  "🪳": "Cockroach.webp",
  "🍸": "Cocktail Glass.webp",
  "⚰️": "Coffin.webp",
  "🪙": "Coin.webp",
  "🥶": "Cold Face.webp",
  "💥": "Collision.webp",
  "🧭": "Compass.webp",
  "🎊": "Confetti Ball.webp",
  "😖": "Confounded Face.webp",
  "😕": "Confused Face.webp",
  "🍪": "Cookie.webp",
  "🍳": "Cooking.webp",
  "🆒": "Cool Button.webp",
  "🐄": "Cow.webp",
  "🤠": "Cowboy Hat Face.webp",
  "🦗": "Cricket.webp",
  "❌": "Cross Mark.webp",
  "🤞": "Crossed Fingers.webp",
  "👑": "Crown.webp",
  "😿": "Crying Cat.webp",
  "😢": "Crying Face.webp",
  "🔮": "Crystal Ball.webp",
  "🥤": "Cup With Straw.webp",
  "🧁": "Cupcake.webp",
  "💱": "Currency Exchange.webp",
  "🍮": "Custard.webp",
  "🛃": "Customs.webp",
  "🍡": "Dango.webp",
  "🌳": "Deciduous Tree.webp",
  "🦌": "Deer.webp",
  "🏝️": "Desert Island.webp",
  "😞": "Disappointed Face.webp",
  "🥸": "Disguised Face.webp",
  "😵": "Dizzy Face.webp",
  "💫": "Dizzy.webp",
  "🐶": "Dog Face.webp",
  "🫥": "Dotted Line Face.webp",
  "‼️": "Double Exclamation Mark.webp",
  "🍩": "Doughnut.webp",
  "🕊️": "Dove.webp",
  "😓": "Downcast Face With Sweat.webp",
  "🤤": "Drooling Face.webp",
  "🦆": "Duck.webp",
  "🦻": "Ear With Hearing Aid.webp",
  "👂": "Ear.webp",
  "🌲": "Evergreen Tree.webp",
  "❗": "Exclamation Mark.webp",
  "⁉️": "Exclamation Question Mark.webp",
  "🤯": "Exploding Head.webp",
  "😑": "Expressionless Face.webp",
  "👀": "Eyes.webp",
  "😘": "Face Blowing A Kiss.webp",
  "😮‍💨": "Face Exhaling.webp",
  "🥲": "Face Holding Back Tears.webp",
  "😶‍🌫️": "Face In Clouds.webp",
  "😋": "Face Savoring Food.webp",
  "😱": "Face Screaming In Fear.webp",
  "🤮": "Face Vomiting.webp",
  "🫤": "Face With Diagonal Mouth.webp",
  "🤭": "Face With Hand Over Mouth.webp",
  "🤕": "Face With Head Bandage.webp",
  "😷": "Face With Medical Mask.webp",
  "🧐": "Face With Monocle.webp",
  "🫢": "Face With Open Eyes And Hand Over Mouth.webp",
  "😮": "Face With Open Mouth.webp",
  "🫣": "Face With Peeking Eye.webp",
  "🤨": "Face With Raised Eyebrow.webp",
  "🙄": "Face With Rolling Eyes.webp",
  "😵‍💫": "Face With Spiral Eyes.webp",
  "😤": "Face With Steam From Nose.webp",
  "🤬": "Face With Symbols On Mouth.webp",
  "😂": "Face With Tears Of Joy.webp",
  "🤒": "Face With Thermometer.webp",
  "😛": "Face With Tongue.webp",
  "😶": "Face Without Mouth.webp",
  "👨‍👩‍👧‍👦": "Family Man Woman Girl Boy.webp",
  "😨": "Fearful Face.webp",
  "📁": "File Folder.webp",
  "🔥": "Fire.webp",
  "🧨": "Firecracker.webp",
  "🎆": "Fireworks.webp",
  "🌓": "First Quarter Moon.webp",
  "🍥": "Fish Cake With Swirl.webp",
  "🐟": "Fish.webp",
  "🇦🇷": "Flag Argentina.webp",
  "🇦🇲": "Flag Armenia.webp",
  "🇦🇹": "Flag Austria.webp",
  "🇧🇸": "Flag Bahamas.webp",
  "🇧🇾": "Flag Belarus.webp",
  "🇧🇪": "Flag Belgium.webp",
  "🇧🇯": "Flag Benin.webp",
  "🇧🇷": "Flag Brazil.webp",
  "🇧🇬": "Flag Bulgaria.webp",
  "🇧🇫": "Flag Burkina Faso.webp",
  "🇨🇲": "Flag Cameroon.webp",
  "🇹🇩": "Flag Chad.webp",
  "🇨🇳": "Flag China.webp",
  "🇨🇮": "Flag Cote Divoire.webp",
  "🇭🇷": "Flag Croatia.webp",
  "🇨🇿": "Flag Czechia.webp",
  "🇩🇯": "Flag Djibouti.webp",
  "🇬🇶": "Flag Equatorial Guinea.webp",
  "🇪🇪": "Flag Estonia.webp",
  "🇫🇷": "Flag France.webp",
  "🇬🇦": "Flag Gabon.webp",
  "🇩🇪": "Flag Germany.webp",
  "🇬🇭": "Flag Ghana.webp",
  "🇬🇼": "Flag Guinea Bissau.webp",
  "🇬🇳": "Flag Guinea.webp",
  "🇭🇺": "Flag Hungary.webp",
  "🇮🇳": "Flag India.webp",
  "🇮🇩": "Flag Indonesia.webp",
  "🇮🇪": "Flag Ireland.webp",
  "🇮🇹": "Flag Italy.webp",
  "🇯🇵": "Flag Japan.webp",
  "🇯🇴": "Flag Jordan.webp",
  "🇱🇹": "Flag Lithuania.webp",
  "🇱🇺": "Flag Luxembourg.webp",
  "🇲🇬": "Flag Madagascar.webp",
  "🇲🇱": "Flag Mali.webp",
  "🇲🇨": "Flag Monaco.webp",
  "🇲🇦": "Flag Morocco.webp",
  "🇲🇿": "Flag Mozambique.webp",
  "🇲🇲": "Flag Myanmar Burma.webp",
  "🇳🇱": "Flag Netherlands.webp",
  "🇳🇬": "Flag Nigeria.webp",
  "🇵🇸": "Flag Palestinian Territories.webp",
  "🇵🇪": "Flag Peru.webp",
  "🇵🇭": "Flag Philippines.webp",
  "🇵🇱": "Flag Poland.webp",
  "🇷🇴": "Flag Romania.webp",
  "🇷🇺": "Flag Russia.webp",
  "🇸🇹": "Flag Sao Tome Principe.webp",
  "🇸🇦": "Flag Saudi Arabia.webp",
  "🇸🇳": "Flag Senegal.webp",
  "🇸🇱": "Flag Sierra Leone.webp",
  "🇸🇬": "Flag Singapore.webp",
  "🇸🇽": "Flag Sint Maarten.webp",
  "🇸🇴": "Flag Somalia.webp",
  "🇰🇷": "Flag South Korea.webp",
  "🇸🇸": "Flag South Sudan.webp",
  "🇪🇸": "Flag Spain.webp",
  "🇸🇩": "Flag Sudan.webp",
  "🇺🇦": "Flag Ukraine.webp",
  "🇦🇪": "Flag United Arab Emirates.webp",
  "🇬🇧": "Flag United Kingdom.webp",
  "🇺🇸": "Flag United States.webp",
  "🇺🇿": "Flag Uzbekistan.webp",
  "🇻🇳": "Flag Vietnam.webp",
  "🇪🇭": "Flag Western Sahara.webp",
  "🇾🇪": "Flag Yemen.webp",
  "🦩": "Flamingo.webp",
  "💪": "Flexed Biceps.webp",
  "😳": "Flushed Face.webp",
  "🙏": "Folded Hands.webp",
  "🦶": "Foot.webp",
  "👣": "Footprints.webp",
  "🍽️": "Fork And Knife With Plate.webp",
  "🍀": "Four Leaf Clover.webp",
  "🦊": "Fox.webp",
  "🆓": "Free Button.webp",
  "🍟": "French Fries.webp",
  "🐸": "Frog.webp",
  "🐥": "Front Facing Baby Chick.webp",
  "😦": "Frowning Face With Open Mouth.webp",
  "☹️": "Frowning Face.webp",
  "🌝": "Full Moon Face.webp",
  "🌕": "Full Moon.webp",
  "💎": "Gem Stone.webp",
  "♊": "Gemini.webp",
  "👻": "Ghost.webp",
  "🦒": "Giraffe.webp",
  "🥛": "Glass Of Milk.webp",
  "🌟": "Glowing Star.webp",
  "👺": "Goblin.webp",
  "🦍": "Gorilla.webp",
  "🎓": "Graduation Cap.webp",
  "💚": "Green Heart.webp",
  "😬": "Grimacing Face.webp",
  "😸": "Grinning Cat With Smiling Eyes.webp",
  "😺": "Grinning Cat.webp",
  "😃": "Grinning Face With Big Eyes.webp",
  "😄": "Grinning Face With Smiling Eyes.webp",
  "😅": "Grinning Face With Sweat.webp",
  "😀": "Grinning Face.webp",
  "😆": "Grinning Squinting Face.webp",
  "💗": "Growing Heart.webp",
  "🍔": "Hamburger.webp",
  "🐹": "Hamster.webp",
  "🖐️": "Hand With Fingers Splayed.webp",
  "🤌": "Hand With Index Finger And Thumb Crossed.webp",
  "👜": "Handbag.webp",
  "🤝": "Handshake.webp",
  "🐣": "Hatching Chick.webp",
  "🙉": "Hear No Evil Monkey.webp",
  "💟": "Heart Decoration.webp",
  "❣️": "Heart Exclamation.webp",
  "🫶": "Heart Hands.webp",
  "❤️‍🔥": "Heart On Fire.webp",
  "💘": "Heart With Arrow.webp",
  "💝": "Heart With Ribbon.webp",
  "🦔": "Hedgehog.webp",
  "🌿": "Herb.webp",
  "🌺": "Hibiscus.webp",
  "👠": "High Heeled Shoe.webp",
  "⚡": "High Voltage.webp",
  "🐝": "Honeybee.webp",
  "🐴": "Horse Face.webp",
  "🐎": "Horse.webp",
  "☕": "Hot Beverage.webp",
  "🌭": "Hot Dog.webp",
  "🥵": "Hot Face.webp",
  "♨️": "Hot Springs.webp",
  "⌛": "Hourglass Done.webp",
  "⏳": "Hourglass Not Done.webp",
  "🏠": "House.webp",
  "🤗": "Hugging Face.webp",
  "💯": "Hundred Points.webp",
  "😯": "Hushed Face.webp",
  "🪪": "Identification Card.webp",
  "📥": "Inbox Tray.webp",
  "📨": "Incoming Envelope.webp",
  "🫵": "Index Pointing At The Viewer.webp",
  "☝️": "Index Pointing Up.webp",
  "🎃": "Jack O Lantern.webp",
  "🦘": "Kangaroo.webp",
  "🔑": "Key.webp",
  "⌨️": "Keyboard.webp",
  "💋": "Kiss Mark.webp",
  "😽": "Kissing Cat.webp",
  "😚": "Kissing Face With Closed Eyes.webp",
  "😗": "Kissing Face.webp",
  "🐨": "Koala.webp",
  "🐞": "Lady Beetle.webp",
  "💻": "Laptop.webp",
  "🌗": "Last Quarter Moon.webp",
  "🤛": "Left Facing Fist.webp",
  "🛅": "Left Luggage.webp",
  "🫲": "Leftwards Hand.webp",
  "🦵": "Leg.webp",
  "♌": "Leo.webp",
  "🐆": "Leopard.webp",
  "♎": "Libra.webp",
  "💡": "Light Bulb.webp",
  "🦁": "Lion.webp",
  "🦙": "Llama.webp",
  "🦞": "Lobster.webp",
  "🔐": "Locked With Key.webp",
  "🚂": "Locomotive.webp",
  "🍭": "Lollipop.webp",
  "😭": "Loudly Crying Face.webp",
  "💌": "Love Letter.webp",
  "🤟": "Love You Gesture.webp",
  "🧳": "Luggage.webp",
  "🤥": "Lying Face.webp",
  "🪄": "Magic Wand.webp",
  "🔍": "Magnifying Glass Tilted Left.webp",
  "🔎": "Magnifying Glass Tilted Right.webp",
  "🕺": "Man Dancing.webp",
  "🤦‍♂️": "Man Facepalming.webp",
  "👨‍⚕️": "Man Health Worker.webp",
  "👮‍♂️": "Man Police Officer.webp",
  "🤷‍♂️": "Man Shrugging.webp",
  "👨‍🏫": "Man Teacher.webp",
  "👨‍💻": "Man Technologist.webp",
  "🧛‍♂️": "Man Vampire.webp",
  "🧟‍♂️": "Man Zombie.webp",
  "🧉": "Mate.webp",
  "🍖": "Meat On Bone.webp",
  "🦾": "Mechanical Arm.webp",
  "🦿": "Mechanical Leg.webp",
  "📣": "Megaphone.webp",
  "🫠": "Melting Face.webp",
  "📝": "Memo.webp",
  "❤️‍🩹": "Mending Heart.webp",
  "🚹": "Mens Room.webp",
  "🦠": "Microbe.webp",
  "🎤": "Microphone.webp",
  "🔬": "Microscope.webp",
  "🖕": "Middle Finger.webp",
  "🪖": "Military Helmet.webp",
  "🎖️": "Military Medal.webp",
  "🪩": "Mirror Ball.webp",
  "🗿": "Moai.webp",
  "📲": "Mobile Phone With Arrow.webp",
  "📱": "Mobile Phone.webp",
  "💰": "Money Bag.webp",
  "🤑": "Money Mouth Face.webp",
  "💸": "Money With Wings.webp",
  "🐵": "Monkey Face.webp",
  "🦟": "Mosquito.webp",
  "🛥️": "Motor Boat.webp",
  "🐭": "Mouse Face.webp",
  "👄": "Mouth.webp",
  "🤶": "Mrs Claus.webp",
  "🎵": "Musical Note.webp",
  "🎶": "Musical Notes.webp",
  "🧑‍🎄": "Mx Claus.webp",
  "💅": "Nail Polish.webp",
  "🤢": "Nauseated Face.webp",
  "🤓": "Nerd Face.webp",
  "😐": "Neutral Face.webp",
  "🆕": "New Button.webp",
  "🌚": "New Moon Face.webp",
  "🌑": "New Moon.webp",
  "📰": "Newspaper.webp",
  "🔞": "No One Under Eighteen.webp",
  "👃": "Nose.webp",
  "🐙": "Octopus.webp",
  "🍢": "Oden.webp",
  "👹": "Ogre.webp",
  "🆗": "Ok Button.webp",
  "👌": "Ok Hand.webp",
  "🗝️": "Old Key.webp",
  "👵": "Old Woman.webp",
  "👊": "Oncoming Fist.webp",
  "📖": "Open Book.webp",
  "👐": "Open Hands.webp",
  "⛎": "Ophiuchus.webp",
  "🧡": "Orange Heart.webp",
  "📤": "Outbox Tray.webp",
  "🦉": "Owl.webp",
  "🐂": "Ox.webp",
  "🫳": "Palm Down Hand.webp",
  "🌴": "Palm Tree.webp",
  "🫴": "Palm Up Hand.webp",
  "🤲": "Palms Up Together.webp",
  "🥞": "Pancakes.webp",
  "🐼": "Panda.webp",
  "🦜": "Parrot.webp",
  "🎉": "Party Popper.webp",
  "🥳": "Partying Face.webp",
  "🛂": "Passport Control.webp",
  "🐾": "Paw Prints.webp",
  "✏️": "Pencil.webp",
  "🐧": "Penguin.webp",
  "😔": "Pensive Face.webp",
  "🫂": "People Hugging.webp",
  "🎭": "Performing Arts.webp",
  "😣": "Persevering Face.webp",
  "🤦": "Person Facepalming.webp",
  "🤷": "Person Shrugging.webp",
  "🥧": "Pie.webp",
  "🐷": "Pig Face.webp",
  "🐽": "Pig Nose.webp",
  "💩": "Pile Of Poo.webp",
  "💊": "Pill.webp",
  "🤏": "Pinching Hand.webp",
  "🏴‍☠️": "Pirate Flag.webp",
  "♓": "Pisces.webp",
  "🍕": "Pizza.webp",
  "🥺": "Pleading Face.webp",
  "🐻‍❄️": "Polar Bear.webp",
  "🚓": "Police Car.webp",
  "🍿": "Popcorn.webp",
  "🍗": "Poultry Leg.webp",
  "🫗": "Pouring Liquid.webp",
  "😾": "Pouting Cat.webp",
  "😡": "Pouting Face.webp",
  "🤰": "Pregnant Woman.webp",
  "🥨": "Pretzel.webp",
  "🖨️": "Printer.webp",
  "💜": "Purple Heart.webp",
  "👛": "Purse.webp",
  "❓": "Question Mark.webp",
  "🐰": "Rabbit Face.webp",
  "🐇": "Rabbit.webp",
  "🦝": "Raccoon.webp",
  "🌈": "Rainbow.webp",
  "🤚": "Raised Back Of Hand.webp",
  "✊": "Raised Fist.webp",
  "✋": "Raised Hand.webp",
  "🙌": "Raising Hands.webp",
  "❤️": "Red Heart.webp",
  "😌": "Relieved Face.webp",
  "🎗️": "Reminder Ribbon.webp",
  "💞": "Revolving Hearts.webp",
  "🍙": "Rice Ball.webp",
  "🍘": "Rice Cracker.webp",
  "🗯️": "Right Anger Bubble.webp",
  "🤜": "Right Facing Fist.webp",
  "🫱": "Rightwards Hand.webp",
  "🤖": "Robot.webp",
  "🚀": "Rocket.webp",
  "🧻": "Roll Of Paper.webp",
  "🎢": "Roller Coaster.webp",
  "🤣": "Rolling On The Floor Laughing.webp",
  "🌹": "Rose.webp",
  "🏵️": "Rosette.webp",
  "😥": "Sad But Relieved Face.webp",
  "♐": "Sagittarius.webp",
  "🫡": "Saluting Face.webp",
  "🥪": "Sandwich.webp",
  "🎅": "Santa Claus.webp",
  "🦕": "Sauropod.webp",
  "♏": "Scorpio.webp",
  "🦭": "Seal.webp",
  "🙈": "See No Evil Monkey.webp",
  "🌱": "Seedling.webp",
  "☘️": "Shamrock.webp",
  "🛍️": "Shopping Bags.webp",
  "🛒": "Shopping Cart.webp",
  "🍰": "Shortcake.webp",
  "🦐": "Shrimp.webp",
  "🤫": "Shushing Face.webp",
  "🤘": "Sign Of The Horns.webp",
  "☠️": "Skull And Crossbones.webp",
  "💀": "Skull.webp",
  "😴": "Sleeping Face.webp",
  "😪": "Sleepy Face.webp",
  "🙁": "Slightly Frowning Face.webp",
  "🙂": "Slightly Smiling Face.webp",
  "😻": "Smiling Cat With Heart Eyes.webp",
  "😇": "Smiling Face With Halo.webp",
  "🥰": "Smiling Face With Hearts.webp",
  "😈": "Smiling Face With Horns.webp",
  "😊": "Smiling Face With Smiling Eyes.webp",
  "😎": "Smiling Face With Sunglasses.webp",
  "☺️": "Smiling Face.webp",
  "😏": "Smirking Face.webp",
  "🐌": "Snail.webp",
  "🐍": "Snake.webp",
  "🤧": "Sneezing Face.webp",
  "❄️": "Snowflake.webp",
  "⛄": "Snowman Without Snow.webp",
  "☃️": "Snowman.webp",
  "🧼": "Soap.webp",
  "⚽": "Soccer Ball.webp",
  "🍦": "Soft Ice Cream.webp",
  "🎇": "Sparkler.webp",
  "✨": "Sparkles.webp",
  "💖": "Sparkling Heart.webp",
  "🙊": "Speak No Evil Monkey.webp",
  "🗣️": "Speaking Head.webp",
  "💬": "Speech Balloon.webp",
  "🕸️": "Spider Web.webp",
  "🕷️": "Spider.webp",
  "🧽": "Sponge.webp",
  "🏅": "Sports Medal.webp",
  "🐳": "Spouting Whale.webp",
  "🦑": "Squid.webp",
  "😜": "Squinting Face With Tongue.webp",
  "🤩": "Star Struck.webp",
  "⭐": "Star.webp",
  "🩺": "Stethoscope.webp",
  "🍓": "Strawberry.webp",
  "🎙️": "Studio Microphone.webp",
  "🥙": "Stuffed Flatbread.webp",
  "⛅": "Sun Behind Cloud.webp",
  "🌥️": "Sun Behind Large Cloud.webp",
  "🌦️": "Sun Behind Rain Cloud.webp",
  "🌤️": "Sun Behind Small Cloud.webp",
  "🌞": "Sun With Face.webp",
  "☀️": "Sun.webp",
  "🍣": "Sushi.webp",
  "🦢": "Swan.webp",
  "💉": "Syringe.webp",
  "🦖": "T Rex.webp",
  "🌮": "Taco.webp",
  "♉": "Taurus.webp",
  "🚕": "Taxi.webp",
  "📆": "Tear Off Calendar.webp",
  "🧑‍💻": "Technologist.webp",
  "📞": "Telephone Receiver.webp",
  "☎️": "Telephone.webp",
  "🔭": "Telescope.webp",
  "📺": "Television.webp",
  "🧪": "Test Tube.webp",
  "🌡️": "Thermometer.webp",
  "🤔": "Thinking Face.webp",
  "💭": "Thought Balloon.webp",
  "👎": "Thumbs Down.webp",
  "👍": "Thumbs Up.webp",
  "🐯": "Tiger Face.webp",
  "🐅": "Tiger.webp",
  "😫": "Tired Face.webp",
  "👅": "Tongue.webp",
  "🧰": "Toolbox.webp",
  "🦷": "Tooth.webp",
  "🔝": "Top Arrow.webp",
  "🎩": "Top Hat.webp",
  "🚩": "Triangular Flag.webp",
  "🏆": "Trophy.webp",
  "🍹": "Tropical Drink.webp",
  "🐠": "Tropical Fish.webp",
  "🌷": "Tulip.webp",
  "🥃": "Tumbler Glass.webp",
  "🦃": "Turkey.webp",
  "🐢": "Turtle.webp",
  "💕": "Two Hearts.webp",
  "😒": "Unamused Face.webp",
  "🦄": "Unicorn.webp",
  "🆙": "Up Button.webp",
  "🙃": "Upside Down Face.webp",
  "🧛": "Vampire.webp",
  "✌️": "Victory Hand.webp",
  "🎮": "Video Game.webp",
  "♍": "Virgo.webp",
  "🖖": "Vulcan Salute.webp",
  "🌘": "Waning Crescent Moon.webp",
  "👋": "Waving Hand.webp",
  "🌒": "Waxing Crescent Moon.webp",
  "🌔": "Waxing Gibbous Moon.webp",
  "🙀": "Weary Cat.webp",
  "😩": "Weary Face.webp",
  "❕": "White Exclamation Mark.webp",
  "🏳️": "White Flag.webp",
  "🤍": "White Heart.webp",
  "❔": "White Question Mark.webp",
  "🍷": "Wine Glass.webp",
  "😉": "Winking Face.webp",
  "💃": "Woman Dancing.webp",
  "🤦‍♀️": "Woman Facepalming.webp",
  "👩‍⚕️": "Woman Health Worker.webp",
  "👮‍♀️": "Woman Police Officer.webp",
  "🤷‍♀️": "Woman Shrugging.webp",
  "👩‍💻": "Woman Technologist.webp",
  "🧛‍♀️": "Woman Vampire.webp",
  "🧟‍♀️": "Woman Zombie.webp",
  "🚺": "Womens Room.webp",
  "🥴": "Woozy Face.webp",
  "😟": "Worried Face.webp",
  "✍️": "Writing Hand.webp",
  "🥱": "Yawning Face.webp",
  "💛": "Yellow Heart.webp",
  "🤪": "Zany Face.webp",
  "🦓": "Zebra.webp",
  "🤐": "Zipper Mouth Face.webp",
  "🧟": "Zombie.webp",
  "💤": "Zzz.webp"
};
